site_name: Class++ Documentation
repo_name: TenebrisNoctua/Class++
repo_url: https://github.com/TenebrisNoctua/ClassPP
theme:
  logo: img/cppicon_v2.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Light Mode
      primary: purple
      accent: purple 

    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Dark Mode 
      primary: purple
      accent: purple
extra_css: [css/extra.css]

markdown_extensions:
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extra
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Tutorials:
    - tutorials/gettingStarted.md
    - Class Creation:
      - tutorials/classCreation.md
      - tutorials/accessSpecifiers.md
      - tutorials/classMethods.md
    - Advanced:
      - tutorials/friendAccessSpecifier.md
      - tutorials/classConstructors.md
      - tutorials/inheritance.md
      - tutorials/operatorOverloading.md
      - tutorials/functionOverloading.md
      - tutorials/nonAccessSpecifiers.md
      - tutorials/staticMembers.md
      - tutorials/polymorphism.md
      - tutorials/errorHandling.md
  - API Reference: 
      - Getting Started: apiReference/gettingStarted.md
      - Class++ Functions: 
        - class: apiReference/classFunctions/mainModule/class.md
        - final: apiReference/classFunctions/mainModule/final.md
        - abstract: apiReference/classFunctions/mainModule/abstract.md
        - getClass: apiReference/classFunctions/mainModule/getClass.md
        - Type: 
          - typeof: apiReference/classFunctions/type/typeof.md
          - typeofClass: apiReference/classFunctions/type/typeofclass.md
        - Util:
          - inClassScope: apiReference/classFunctions/util/inClassScope.md
          - checkInheritance: apiReference/classFunctions/util/checkInheritance.md
          - checkFriendship: apiReference/classFunctions/util/checkFriendship.md
      - Data Types:
        - apiReference/dataTypes/class.md
        - apiReference/dataTypes/object.md
      - Types:
        - apiReference/types/classData.md
copyright: |
  &copy; 2024 <a href="https://github.com/TenebrisNoctua"  target="_blank" rel="noopener">Tenebris Noctua</a>