site_name: Class++ Documentation
site_url: https://tenebrisnoctua.github.io/ClassPP/
repo_name: TenebrisNoctua/Class++
repo_url: https://github.com/TenebrisNoctua/ClassPP

extra:
  version:
    provider: mike

theme:
  logo: img/light/classpp_small.png
  logo_dark: img/dark/classpp_small.png
  favicon: img/dark/classpp_fav.png
  custom_dir: docs/overrides
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.indexes 
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: classppdoc-dark
      toggle:
        icon: octicons/sun-24
        name: Switch to Light Mode

    - scheme: classppdoc-light 
      toggle:
        icon: octicons/moon-24
        name: Switch To Dark Mode
  icon:
    repo: octicons/mark-github-16

extra_css:
  - css/colors.css
  - css/theme.css
  - css/code.css
  - css/api-reference.css
  - css/paragraph.css
  - css/home.css

markdown_extensions:
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extra
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Basics:
      - tutorials/basics/classCreation.md
      - tutorials/basics/accessSpecifiers.md
      - tutorials/basics/classMethods.md
      - tutorials/basics/classConstructors.md
    - Advanced:
      - tutorials/advanced/friendAccessSpecifier.md
      - tutorials/advanced/inheritance.md
      - tutorials/advanced/operatorOverloading.md
      - tutorials/advanced/functionOverloading.md
      - tutorials/advanced/nonAccessSpecifiers.md
      - tutorials/advanced/staticMembers.md
      - tutorials/advanced/types.md
    - Best Practices:
      - tutorials/best-practices/encapsulation.md
      - tutorials/best-practices/polymorphism.md
      - tutorials/best-practices/composition.md
      - tutorials/best-practices/errorHandling.md
      - tutorials/best-practices/optimization.md
  - API Reference:
      - API Reference: api-reference/index.md
      - General:
        - Errors: api-reference/general/errors.md
        - version: api-reference/general/version.md
        - autoObjectDestruction: api-reference/general/autoObjectDestruction.md
      - Functions: 
        - class: api-reference/class-functions/main/class.md
        - getClass: api-reference/class-functions/main/getClass.md
        - final: api-reference/class-functions/main/final.md
        - abstract: api-reference/class-functions/main/abstract.md
        - Type: 
          - type: api-reference/class-functions/type/type.md
          - typeof: api-reference/class-functions/type/typeof.md
        - Utility:
          - inClassScope: api-reference/class-functions/utility/inClassScope.md
          - checkInheritance: api-reference/class-functions/utility/checkInheritance.md
          - checkFriendship: api-reference/class-functions/utility/checkFriendship.md
      - Data Types:
        - api-reference/data-types/class.md
        - api-reference/data-types/object.md
      - Types:
        - api-reference/types/classData.md
        - api-reference/types/version.md
copyright: |
  &copy; 2025 <a href="https://github.com/TenebrisNoctua"  target="_blank" rel="noopener">Tenebris Noctua</a>