site_name: Class++ Documentation
repo_name: TenebrisNoctua/Class++
repo_url: https://github.com/TenebrisNoctua/ClassPP

extra:
  version:
    provider: mike

theme:
  logo: img/light/classpp_small.png
  logo_dark: img/dark/classpp_small.png
  favicon: img/dark/classpp_fav.png
  custom_dir: docs/overrides
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.indexes 
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: classppdoc-dark
      toggle:
        icon: octicons/light-bulb-24
        name: Switch to Light Mode

    - scheme: classppdoc-light 
      toggle:
        icon: octicons/moon-24
        name: Switch To Dark Mode
  icon:
    repo: octicons/mark-github-16

extra_css:
  - css/colors.css
  - css/theme.css
  - css/code.css
  - css/api-reference.css
  - css/paragraph.css
  - css/home.css

markdown_extensions:
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extra
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Class Creation:
      - tutorials/classCreation.md
      - tutorials/accessSpecifiers.md
      - tutorials/classMethods.md
    - Advanced:
      - tutorials/friendAccessSpecifier.md
      - tutorials/classConstructors.md
      - tutorials/inheritance.md
      - tutorials/operatorOverloading.md
      - tutorials/functionOverloading.md
      - tutorials/nonAccessSpecifiers.md
      - tutorials/staticMembers.md
      - tutorials/polymorphism.md
      - tutorials/types.md
  - API Reference:
      - API Reference: api-reference/index.md
      - General:
        - Errors: api-reference/errors.md
      - Class++ Functions: 
        - class: api-reference/classFunctions/mainModule/class.md
        - final: api-reference/classFunctions/mainModule/final.md
        - abstract: api-reference/classFunctions/mainModule/abstract.md
        - getClass: api-reference/classFunctions/mainModule/getClass.md
        - Type: 
          - type: api-reference/classFunctions/type/type.md
          - typeof: api-reference/classFunctions/type/typeof.md
        - Util:
          - inClassScope: api-reference/classFunctions/util/inClassScope.md
          - checkInheritance: api-reference/classFunctions/util/checkInheritance.md
          - checkFriendship: api-reference/classFunctions/util/checkFriendship.md
      - Data Types:
        - api-reference/dataTypes/class.md
        - api-reference/dataTypes/object.md
      - Types:
        - api-reference/types/classData.md
copyright: |
  &copy; 2024 <a href="https://github.com/TenebrisNoctua"  target="_blank" rel="noopener">Tenebris Noctua</a>